package checks

import (
	"slices"
	"testing"
)

func TestNoAICoauthor_RejectsAnAI(t *testing.T) {
	for _, line := range []string{
		"Co-Authored-By: Claude Opus 5.5 <noreply@anthropic.com>",
		"Co-authored-by: Claude <noreply@anthropic.com>",
		"co-authored-by: Claude Code <x@y.z>",
		"Co-authored-by: claude <claude@example.com>",
		"Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>",
		"Co-authored-by: Cursor Agent <cursoragent@cursor.com>",
		"Co-authored-by: Codex <codex@openai.com>",
		"Co-authored-by: devin-ai-integration[bot] <158243242+devin-ai-integration[bot]@users.noreply.github.com>",
		"Co-authored-by: gemini-code-assist[bot] <176961590+gemini-code-assist[bot]@users.noreply.github.com>",
		"Co-authored-by: aider (anthropic/claude-sonnet-5-5) <noreply@aider.chat>",
		"Co-authored-by: Amp <amp@ampcode.com>",
		"🤖 Generated with [Claude Code](https://claude.com/claude-code)",
		"Generated with Claude Code",
		"Generated by GitHub Copilot",
		"Generated with Claude",
		"Generated with [Claude](https://claude.ai)",
		"🤖 Generated with some tool",
	} {
		t.Run(line, func(t *testing.T) {
			if got := NoAICoauthor("feat: x\n\nBody.\n\n" + line + "\n"); !slices.Equal(got, []string{line}) {
				t.Errorf("NoAICoauthor = %q, want %q", got, []string{line})
			}
		})
	}
}

func TestNoAICoauthor_AcceptsAPerson(t *testing.T) {
	for _, line := range []string{
		"Co-authored-by: Jane Doe <jane@example.com>",
		"Co-authored-by: Claude Dupont <claude@example.fr>",
		"Co-authored-by: Devin Smith <devin@example.com>",
		"  co-authored-by: indented <x@y.z>",
		"Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>",
		"Generated by the schema compiler.",
		"docs: say Claude Code wrote nothing",
	} {
		t.Run(line, func(t *testing.T) {
			if got := NoAICoauthor("feat: x\n\n" + line + "\n"); got != nil {
				t.Errorf("NoAICoauthor = %q, want none", got)
			}
		})
	}
}

func TestNoAICoauthor_IgnoresTheDiffBelowTheScissors(t *testing.T) {
	message := "feat: x\n# ------------------------ >8 ------------------------\n" +
		"+Co-Authored-By: Claude Opus 5.5 <noreply@anthropic.com>\n" +
		"Co-Authored-By: Claude Opus 5.5 <noreply@anthropic.com>\n"
	if got := NoAICoauthor(message); got != nil {
		t.Errorf("NoAICoauthor = %q, want none", got)
	}
}
