package checks

import (
	"regexp"
	"strings"
)

// ai is an AI named in a co-author trailer or a credit line: Claude with a model, Code or its
// email, or a coding agent by a name or an email no person has.
var ai = regexp.MustCompile(`(?i)\bclaude (code|opus|sonnet|haiku|fable|\d)|@anthropic\.com|` +
	`\bcopilot\b|\bcursor agent\b|@cursor\.(com|sh)|\bchatgpt\b|\bcodex\b|@openai\.com|` +
	`\bgemini\b|devin-ai-integration|\baider\b|@ampcode\.com`)

var (
	// coauthor is a co-author trailer, with the co-author's name.
	coauthor = regexp.MustCompile(`(?i)^\s*co-authored-by:\s*([^<]*?)\s*(<|$)`)
	// credit is a line crediting a tool with the commit: `Generated with …`, `🤖 Generated by …`.
	credit = regexp.MustCompile(`(?i)^\s*(🤖\s*)?generated (with|by)\s`)
	robot  = regexp.MustCompile(`^\s*🤖`)
	claude = regexp.MustCompile(`(?i)\bclaude\b`)
	// scissors is where `git commit -v` puts the diff below the message.
	scissors = regexp.MustCompile(`(?m)^# -+ >8 -+$`)
)

// NoAICoauthor is the Check baloo:no-ai-coauthor (commit-msg): the lines of the commit message
// that make an AI its co-author or credit one with it. A person's co-author trailer passes, even
// one named Claude with a surname; a co-author named only Claude is the AI. In a credit line a
// bare Claude is the AI too, since a person generates no commit, and the robot always marks one.
func NoAICoauthor(message string) []string {
	var found []string
	message = scissors.Split(message, 2)[0]
	for _, line := range strings.Split(message, "\n") {
		if m := coauthor.FindStringSubmatch(line); m != nil {
			if ai.MatchString(line) || strings.EqualFold(m[1], "claude") {
				found = append(found, line)
			}
		} else if credit.MatchString(line) &&
			(ai.MatchString(line) || claude.MatchString(line) || robot.MatchString(line)) {
			found = append(found, line)
		}
	}
	return found
}
